// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TabOut
{
    internal sealed partial class Vsix
    {
        public const string Id = "TabOut.97c51f42-4a79-4529-a3d5-43a249d0e2b8";
        public const string Name = "TabOut";
        public const string Description = @"仿 VS Code TabOut 插件";
        public const string Language = "zh-CN";
        public const string Version = "2.4.2";
        public const string Author = "穿越中的逍遥";
        public const string Tags = "";
    }
}
